<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<RootNamespace>MultiplayerDemo.Server</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\MultiplayerDemo.Core\MultiplayerDemo.Core.csproj" />
	</ItemGroup>

</Project>
